### PR TITLE
create a bio for Estherbunny

### LINKED ISSUE #39: Add bio for Estherbunny
### Things to include

**everything i like to do**

- [ ] eat
- [ ] sleep
- [ ] rave
- [ ] repeat

@githubteacher should i add anything else?

### PR DESCRIPTION
**Pull request by Estherbunny**
Resolves #39 

Adding a bio for Estherbunny

@larissasimplyhired what else do you think i should add?

### CODE REVIEW

**Comment by larissasimplyhired** [comment]
- redbull :)

**Comment by larissasimplyhired** [comment]
lol sugar free :)

**Comment by larissasimplyhired** [comment]
LGTM

**Comment by wgannon-sjrwmd** [comment]
comment comment blah blah blah

**Comment by larissasimplyhired** [comment]
:shipit:

**Comment by wgannon-sjrwmd** [comment]
:+1: go fot it

**Comment by Estherbunny** [comment]
thanks! will ship! :rocket:

**Pull request merged**
